### ISSUE TITLE
Lume pad 2 citra- touchscreen misalligned

### ISSUE THREAD

**Issue by guyrv** [jakedowns/citra-4v#5]
Hi I really love your work thank you for putting time into the lume pad.

As the title says. I am using the lume pad 2 citra- apk from may 10th. It is working great except the touch screen seems misalligned in every possible layout.  Hit point seems to hit anywhere from 1 inch to 5 inches left of finger.

I tried your lume pad 1 apk and everything  works except the 3d. 

Not sure if you were aware. Thanks again.

**Comment by jakedowns** [comment]
thanks for the report! i'm gonna close this one as it's a duplicate, but I _am_ tracking it over in the current repo:

https://github.com/jakedowns/citra/issues/10
